title:             Dong Xin 's Personal Website
email:             tonydong321@qq.com
description:       眼前的黑不是黑 你说的白是什么白
author:            tonydong
#baseurl:           "/"
#url:               "localhost:4000"

# Social Profiles
twitter_username:  DongTonydong321
github_username:   tonyDx
facebook_username: 100011372958185

# Build settings
markdown:          kramdown
permalink: pretty
highlighter: rouge


paginate:          8
paginate_path:     "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate


lean_cloud :
  app_id   :  2tHkLRdCcjpBhkGgU60bshd2-gzGzoHsz
  app_key  :  hUBGYOJCIejnPGh4lNe1gkbB