title:             Dong Xin 's Personal Website
email:             tonydong321@qq.com
description:       眼前的黑不是黑 你说的白是什么白
author:            tonydong
#baseurl:           ""
#url:               ""

# Social Profiles
twitter_username:  DongTonydong321
github_username:   tonyDx
facebook_username: 100011372958185

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
